
CREATE TABLE USER_TABLE
(
  SID BIGINT(19) PRIMARY KEY AUTO_INCREMENT COMMENT '用户id',
	USER_ACCOUNT VARCHAR(64) NOT NULL UNIQUE COMMENT '用户账号',
	USER_PWD VARCHAR(64) NOT NULL COMMENT '用户密码',
	USER_UUID VARCHAR(64) NOT NULL UNIQUE COMMENT '用户唯一id',
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE = InnoDB AUTO_INCREMENT = 1000 CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = '用户表';

CREATE TABLE ROLE_TABLE
(
  SID BIGINT(19) PRIMARY KEY AUTO_INCREMENT COMMENT '角色id',
	ROLE_NAME VARCHAR(64) NOT NULL COMMENT '角色名',
	CREATE_MAN_UUID VARCHAR(64) NOT NULL COMMENT '创建者id',
	ROLE_UUID VARCHAR(64) NOT NULL UNIQUE COMMENT '角色唯一id',
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE = InnoDB AUTO_INCREMENT = 1000 CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = '角色表';

CREATE TABLE PERMISSION_TABLE
(
  SID BIGINT(19) PRIMARY KEY AUTO_INCREMENT COMMENT '权限id',
	PERMISSION_UUID VARCHAR(64) NOT NULL UNIQUE COMMENT '权限唯一id',
	RESOURCE_UUID VARCHAR(64) NOT NULL COMMENT '资源唯一id',
	RESOURCE_TYPE_UUID VARCHAR(64) NOT NULL COMMENT '资源类型唯一id，比如用户、页面',
	RESOURCE_PRIVILEGES VARCHAR(16) NOT NULL COMMENT '对资源拥有的操作',
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE = InnoDB AUTO_INCREMENT = 1000 CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = '权限表';

CREATE TABLE USER_ROLE_TABLE
(
  SID BIGINT(19) PRIMARY KEY AUTO_INCREMENT COMMENT '关联表id',
	USER_UUID VARCHAR(64) NOT NULL COMMENT '用户唯一id',
	ROLE_UUID VARCHAR(64) NOT NULL COMMENT '角色唯一id',
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE = InnoDB AUTO_INCREMENT = 1000 CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = '用户角色关联表';

CREATE TABLE ROLE_PERMISSION_TABLE
(
  SID BIGINT(19) PRIMARY KEY AUTO_INCREMENT COMMENT '关联表id',
	ROLE_UUID VARCHAR(64) NOT NULL COMMENT '角色唯一id',
	PERMISSION_UUID VARCHAR(64) NOT NULL COMMENT '权限唯一id',
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE = InnoDB AUTO_INCREMENT = 1000 CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = '角色权限关联表';