server:
  port: 8085
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: dev
  datasource:
    platform: mysql
    url: jdbc:mysql://172.17.50.101:3306/camera?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat
      maxActive: 10
      initialSize: 1
      maxWait: 5000
      minIdle: 10
      maxIdle: 15
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      maxOpenPreparedStatements: 20
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true

  freemarker:
    request-context-attribute: req
    suffix: .ftl
    content-type: text/html
    enabled: true
    cache: false
    check-template-location: true
    template-loader-path: classpath:/templates/
    charset: UTF-8
    settings:
      number_format: '0.##'
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

  mvc:
    static-path-pattern: /static/**
  redis:
    url:
    timeout: 1000ms
    ssl: false
    port:
    password:
    host:
    database: 0
    cluster:
      nodes: 6
    cluster:
      max-redirects: 3
    lettuce:
      shutdown-timeout: 100ms
      pool:
        min-idle: 0
      pool:
        max-wait: -1ms
      pool:
        max-idle: 8
      pool:
        max-active: 8
  jms:
    pub-sub-domain: true
    listener:
      acknowledge-mode: auto
      concurrency: 3
      max-concurrency: 7
    cache:
      enabled: true
      session-cache-size: 5
      producers: true
      consumers: true
  messages:
    basename: i18n/Messages,i18n/Pages
  activemq:
    broker-url:
    password:
    user:
    in-memory: false
    close-timeout: 5s
    pool:
      enabled: true
      idle-timeout: 5s
      time-between-expiration-check: -1ms
      max-connections: 5
      max-sessions-per-connection: 500


mybatis:
  typeAliasesPackage: com.kelan.smallscene.dao
  mapperLocations: classpath:mapper/*.xml
  configLocation: classpath:mybatis/mybatis-config.xml



