server:
  port: 8085
  servlet:
    context-path: /

spring:
  profiles:
    active: dev
  datasource:
    platform: mysql
    url: jdbc:mysql://172.17.50.101:3306/camera?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat
      maxActive: 10
      initialSize: 1
      maxWait: 5000
      minIdle: 10
      maxIdle: 15
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      maxOpenPreparedStatements: 20
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true

#  freemarker:
#    request-context-attribute: req
#    suffix: .html
#    content-type: text/html
#    enabled: true
#    cache: false
#    check-template-location: true
#    template-loader-path: classpath:/templates/
#    charset: UTF-8
#    settings:
#      number_format: '0.##'
  mvc:
    view:
      prefix: /
      suffix: .jsp
mybatis:
  typeAliasesPackage: com.kelan.smallscene.dao
  mapperLocations: classpath:mapper/*.xml
  configLocation: classpath:mybatis/mybatis-config.xml



